### PR TITLE
Update PRESTO_S3_IAM_ROLE config key name in PrestoFileSystemCache

### PR DESCRIPTION
**Pull request by imjalpreet**
Updated the Presto S3 IAM Role configuration key name to the same that is being used in Presto now.

### CODE REVIEW

**Comment by imjalpreet** [comment]
@rschlussel Can you please review this PR whenever you get time? It's a minor fix

**Review by rschlussel — APPROVED** [review]
I apologize for the delay.  I was on leave when this came in and only just noticed the review request.

**Comment by imjalpreet** [comment]
@rschlussel No problem, thanks for looking into this. Can we also release a new version so that I can include it in Presto?

**Comment by rschlussel** [comment]
Updated the version.  Just waiting for approval to deploy new artifacts.

**Comment by tdcmeehan** [comment]
@imjalpreet a new release `2.7.4-11` was cut and should be in Maven central shortly.

**Pull request merged**
