### PR TITLE
Bump Hadoop to 2.7.1

### PR DESCRIPTION
**Pull request by mandusm**
Bumping Hadoop Dependency to 2.7.1 which includes multiple RecordReader fixes for Hive.

### CODE REVIEW

**Comment by electrum** [comment]
Merged, thanks!

**Comment by mandusm** [comment]
We should retract this pull, there is an issue with S3 communications in the hive connector since the bump to 2.7.1

This is because the reordering in hadoop from 2.2.0 - 2.6.0 where hadoop-aws as a package was introduced. 

Busy fixing this.

**Comment by mandusm** [comment]
Fixed the S3 dependency issues in this pull request: https://github.com/prestodb/presto-hadoop-apache2/pull/6

**Comment by mandusm** [comment]
I fixed the dependency issues for S3 in my Latest Pull Request #7

**Pull request closed without merging**
