### PR TITLE
Fixed Hadoop 2.7.1 Dependencies for S3.

### PR DESCRIPTION
**Pull request by mandusm**
Added hadoop-aws package to satisfy dependencies for querying data in S3. 
Successful tests now include S3 and HDFS bzip2 data being queried from Presto 0.128

#### S3 Based Query 
```
presto:default> select col1, col2, col3, col57 from s3_bz2_table where mydate = cast('2015-06-01' as date) limit 10;
    col1    |    col2    |   col3   |  col57   
------------+------------+----------+----------
 row_926749 | 2015-06-01 | 56993665 | 9310.345 
 row_926750 | 2015-06-01 | 56993665 | 479.398  
 row_926751 | 2015-06-01 | 56993665 | 2106.145 
 row_926752 | 2015-06-01 | 56993665 | 873.714  
 row_926753 | 2015-06-01 | 56993665 | 127.1049 
 row_926754 | 2015-06-01 | 56993665 | 6610.957 
 row_926755 | 2015-06-01 | 56993665 | 771.794  
 row_926756 | 2015-06-01 | 56993665 | 939.725  
 row_926757 | 2015-06-01 | 56993665 | 387.686  
 row_926758 | 2015-06-01 | 56993665 | 541.6710 
(10 rows)

Query 20151210_124803_00016_6n8gx, FINISHED, 2 nodes
Splits: 191 total, 20 done (10.47%)
0:10 [70.5K rows, 10.7MB] [6.78K rows/s, 1.03MB/s]
```

#### HDFS Test Query
```
presto:default> select col1, col2, col3, col57 from hdfs_bz2_table where mydate = cast('2015-06-01' as date) limit 10;
    col1     |    col2    |   col3   |  col57   
-------------+------------+----------+----------
 row_3243936 | 2015-06-01 | 56993665 | 439.915  
 row_3243937 | 2015-06-01 | 56993665 | 196.372  
 row_3243938 | 2015-06-01 | 56993665 | 671.254  
 row_3243939 | 2015-06-01 | 56993665 | 1067.518 
 row_3243940 | 2015-06-01 | 56993665 | 351.992  
 row_3243941 | 2015-06-01 | 56993665 | 819.286  
 row_3243942 | 2015-06-01 | 56993665 | 966.288  
 row_3243943 | 2015-06-01 | 56993665 | 552.238  
 row_3243944 | 2015-06-01 | 56993665 | 568.995  
 row_3243945 | 2015-06-01 | 56993665 | 449.164  
(10 rows)

Query 20151210_125820_00002_8ejfu, FINISHED, 2 nodes
Splits: 191 total, 2 done (1.05%)
0:09 [28.7K rows, 4.39MB] [3.08K rows/s, 484KB/s]
```

### CODE REVIEW

**Comment by electrum** [comment]
Is this needed after my change in Presto to remove the dependency on S3Credentials?

**Comment by mandusm** [comment]
Yes, without this commit, if you try to query data in S3 you will get an error like: 

```
2015-12-11T08:32:22.056Z	WARN	hive-hive-0	com.facebook.presto.hive.util.ResumableTasks	ResumableTask completed exceptionally
java.lang.NoClassDefFoundError: org/apache/hadoop/fs/s3/S3Credentials
	at com.facebook.presto.hive.PrestoS3FileSystem.getAwsCredentials(PrestoS3FileSystem.java:638)
	at com.facebook.presto.hive.PrestoS3FileSystem.getAwsCredentialsProvider(PrestoS3FileSystem.java:624)
	at com.facebook.presto.hive.PrestoS3FileSystem.createAmazonS3Client(PrestoS3FileSystem.java:576)
	at com.facebook.presto.hive.PrestoS3FileSystem.initialize(PrestoS3FileSystem.java:185)
	at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:74)
	at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:61)
	at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:43)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:53)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:298)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:210)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:68)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:166)
```

**Comment by electrum** [comment]
Can you try with the latest master? It should be fixed here:

https://github.com/facebook/presto/commit/57ebd0d7a811b544ad72beac80a805a49b3ac432

**Comment by mandusm** [comment]
Ahh, okay. Didn't see the changes in main presto project.
Against HEAD it's working. Wasn't working against 0.129 
Cool. Will close this.

**Pull request closed without merging**
