### PR TITLE
Add Hadoop modules that the presto-accumulo module needs

### PR DESCRIPTION
**Pull request by z-york**
This allows a standardized hadoop version across all of the presto connectors.

### CODE REVIEW

**Comment by z-york** [comment]
@electrum Can you take a look please? This is a prereq for https://github.com/prestodb/presto/pull/6705

**Comment by z-york** [comment]
@electrum @martint Can someone please look at this? This is a fairly simple change. I would like to move past this and be able to work on other stuff.

**Comment by z-york** [comment]
@electrum @martint @cberner Ping!

**Comment by electrum** [comment]
@z-york Sorry the delay. Been busy with some other issues and will get to this soon. Thanks for working on this.

**Comment by z-york** [comment]
@electrum Thanks for looking at this. Any updates?

**Comment by z-york** [comment]
@electrum Any chance you can take a look soon?

**Comment by z-york** [comment]
@electrum Please can you take a look? Thanks!

**Comment by z-york** [comment]
@electrum @martint @cberner Please can someone take a look? This PR has been open for a long time.

**Comment by electrum** [comment]
Apologies for the long delay. I'm looking at this now.

**Comment by electrum** [comment]
I'm not sure we actually need to make any changes here.

After some digging, I found that `hadoop-client` and `hadoop-minicluster` have empty jars! The POMs are simply a list of dependencies with lots of exclusions -- presumably a cleaned up list for use with Maven's `import` scope in a `<dependencyManagement>` section (though all the examples I could find use it wrong). This brings up the question of why they used `jar` packaging rather than `pom` and needlessly produced an empty jar (and this might actually prevent it from being used in `import` scope).

This leaves `hadoop-auth`, which is already included, and the dependencies should be fine since the Accumulo connector excludes all of them.

**Comment by electrum** [comment]
I put up a new PR for Presto: https://github.com/prestodb/presto/pull/7324

**Comment by electrum** [comment]
I'm closing this now that all of Presto is using ZooKeeper 3.4.9 (and the Accumulo works with it). If you see any issues or need anything else, please let us know. Sorry for the long delay getting this resolved!

**Pull request closed without merging**
