### PR TITLE
Add hadoop native lib for linux-aarch64 (ARM)

### PR DESCRIPTION
**Pull request by beinan**
Based on @JunLuo 's https://github.com/prestodb/presto-hadoop-apache2/pull/58.  This PR will fix the clib compatibility issue on centos7

Tested on centos7.

The build steps of the native jars (on centos7 for better compatibility)

```
Build Hadoop Native on Arm

Install protobuf 2.5
Sudo yum --disablerepo=kubernetes install protobuf   


sudo yum group install "Development Tools"

sudo yum install zlib-devel  --disablerepo=kubernetes

sudo yum install bzip2-devel  --disablerepo=kubernetes

sudo yum install openssl  --disablerepo=kubernetes
sudo yum install openssl-devel  --disablerepo=kubernetes

mvn package -Pdist,native -DskipTests -Dtar -Drequire.snappy -Drequire.bzip2


Find the dylib in hadoop/hadoop-dist/target/hadoop-2.7.4/lib/native/libhadoop.so.1.0.0


Check native lib 
./bin/hadoop checknative -a

```

### CODE REVIEW

**Comment by beinan** [comment]
@yingsu00 @7c00 looks like you two are also working on the arm related stuff, could you help take a look? thanks!

**Review by ChunxuTang — COMMENTED** [review]
@beinan Do you also want to check in the build steps, e.g. as a readme of a shell script?

**Comment by beinan** [comment]
> @beinan Do you also want to check in the build steps, e.g. as a readme of a shell script?

Good call!  will try to add a build.sh, thanks!

**Comment by 7c00** [comment]
@beinan I don't have an ARM Linux device, but could help test it in the Linux VM in my Apple M1 device. It would be much better to have a build script (for [example](https://github.com/7c00/libhadoop-macos-arm64/blob/main/build.sh)) to reproduce the tests.

> @yingsu00 @7c00 looks like you two are also working on the arm related stuff, could you help take a look? thanks!

**Comment by ChunxuTang** [comment]
This feature is very essential for running Presto on CentOS. As @beinan has provided the build instructions, may we merge this PR? Cc @7c00 @yingsu00 

@beinan Would you mind later creating a script to automate the build process? Thanks!

**Review by ChunxuTang — APPROVED** [review]

**Pull request merged**
