### PR TITLE
Add native Hadoop and Snappy libraries for macos-aarch64

### PR DESCRIPTION
**Pull request by 7c00**
The native library files were cross-compiled using GitHub action https://github.com/7c00/libhadoop-macos-arm64/actions/runs/2637081130, where the artifact `libhadoop` ([download](https://github.com/7c00/libhadoop-macos-arm64/suites/7277477642/artifacts/293035532)) contains the files and their checksums. 

The build ([script](https://github.com/7c00/libhadoop-macos-arm64/blob/main/build.sh))  is supposed to be reproducible. 

`TestHadoopNative` passed in my MacBook Pro (14-inch, 2021) Apple M1 Pro

### CODE REVIEW

**Comment by 7c00** [comment]
Hi, @beinan, could you take a review on this PR when you get a chance?

**Review by yingsu00 — APPROVED** [review]
Thank  you @7c00 for adding these Aarch64 libraries! I wonder if we should also merge the build.sh you used to build the libraries. @beinan @rongrong @tdcmeehan What do you think?

**Comment by yingsu00** [comment]
Resolves https://github.com/prestodb/presto/issues/18031

**Comment by yingsu00** [comment]
cc @ bmckennaah Can you try to see if these libraries work?

**Review by beinan — APPROVED** [review]
lgtm, but I'm afraid I don't have a arm mac to test it

**Comment by beinan** [comment]
We found this native lib is not working on centos 7, we think it's caused by gcc version conflict.  I guess the lib were built by the newer version of gcc which might be not compatible with some of the mainstream os such as centos 7.

**Review by beinan — CHANGES_REQUESTED** [review]
I might try to rebuild this dylib with a older version of gcc for better compatibility.

**Review by beinan — APPROVED** [review]
my bad, pls ignore my previous review, I thought this one is the pr for linux.

**Comment by beinan** [comment]
hello @7c00 and @yingsu00 ,  

I tried this one on macbook m1,  but I got the failure below when I run the test

```
mvn install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] -------------< com.facebook.presto.hadoop:hadoop-apache2 >--------------
[INFO] Building hadoop-apache2 2.7.4-11-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (default) @ hadoop-apache2 ---
[INFO] Skipping Rule Enforcement.
[INFO]
[INFO] --- dependency-scope-maven-plugin:0.8:check (default) @ hadoop-apache2 ---
[INFO] No test dependency scope issues found
[INFO]
[INFO] --- license-maven-plugin:2.3:check (default) @ hadoop-apache2 ---
[INFO] Checking licenses...
[INFO]
[INFO] --- maven-checkstyle-plugin:3.0.0:check (checkstyle) @ hadoop-apache2 ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (default) @ hadoop-apache2 ---
[INFO] argLine set to -javaagent:/Users/beinanwang/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/Users/beinanwang/w/presto-hadoop-apache2/target/jacoco.exec
[INFO]
[INFO] --- git-commit-id-plugin:2.1.13:revision (default) @ hadoop-apache2 ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hadoop-apache2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ hadoop-apache2 ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hadoop-apache2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/beinanwang/w/presto-hadoop-apache2/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ hadoop-apache2 ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-dependency-plugin:3.1.1:analyze-only (default) @ hadoop-apache2 ---
[INFO] Skipping plugin execution
[INFO]
[INFO] --- maven-dependency-plugin:3.1.1:analyze-duplicate (default) @ hadoop-apache2 ---
[INFO] Skipping plugin execution
[INFO]
[INFO] --- maven-dependency-plugin:3.1.1:analyze-dep-mgt (default) @ hadoop-apache2 ---
[INFO] Skipping plugin execution
[INFO]
[INFO] --- duplicate-finder-maven-plugin:1.2.1:check (default) @ hadoop-apache2 ---
[INFO] Skipping duplicate-finder execution!
[INFO]
[INFO] --- modernizer-maven-plugin:1.7.1:modernizer (modernizer) @ hadoop-apache2 ---
[INFO] Skipping modernizer execution!
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ hadoop-apache2 ---
[INFO] Surefire report directory: /Users/beinanwang/w/presto-hadoop-apache2/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNGMapConfigurator@78a773fd
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.facebook.presto.hadoop.HadoopFileSystemCache (file:/Users/beinanwang/w/presto-hadoop-apache2/target/classes/) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of com.facebook.presto.hadoop.HadoopFileSystemCache
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-09-18T04:14:40.618+0000 WARNING Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2022-09-18T04:14:41.180+0000 WARNING Failed to load/initialize native-bzip2 library system-native, will use pure-Java version
2022-09-18T04:14:41.183+0000 INFO Successfully loaded & initialized native-zlib library
2022-09-18T04:14:41.194+0000 INFO Got brand-new compressor [.bz2]
2022-09-18T04:14:41.214+0000 INFO Got brand-new decompressor [.bz2]
2022-09-18T04:14:41.222+0000 INFO Got brand-new compressor [.deflate]
2022-09-18T04:14:41.224+0000 INFO Got brand-new decompressor [.deflate]
2022-09-18T04:14:41.225+0000 INFO Got brand-new compressor [.gz]
2022-09-18T04:14:41.225+0000 INFO Got brand-new decompressor [.gz]
2022-09-18T04:14:41.227+0000 INFO Got brand-new compressor [.lz4]
2022-09-18T04:14:41.227+0000 INFO Got brand-new decompressor [.lz4]
2022-09-18T04:14:41.228+0000 INFO Got brand-new compressor [.snappy]
2022-09-18T04:14:41.228+0000 INFO Got brand-new decompressor [.snappy]
Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.049 sec <<< FAILURE!
testNative(com.facebook.presto.hadoop.TestHadoopNative)  Time elapsed: 0.019 sec  <<< FAILURE!
java.lang.AssertionError: expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at org.testng.Assert.assertTrue(Assert.java:47)
	at com.facebook.presto.hadoop.TestHadoopNative.testNative(TestHadoopNative.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:241)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1169)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1094)
	at org.testng.TestNG.run(TestNG.java:1006)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   testNative(com.facebook.presto.hadoop.TestHadoopNative): expected:<true> but was:<false>

Tests run: 11, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.325 s
[INFO] Finished at: 2022-09-17T21:14:41-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project hadoop-apache2: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/beinanwang/w/presto-hadoop-apache2/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```


Looks like the bzip not loaded, I guess build the hadoop native with -Drequire.bzip2 might fix the issue.  
```
mvn package -Pdist,native -DskipTests -Dtar -Drequire.snappy -Drequire.bzip2
```

**Comment by 7c00** [comment]
@beinan bzip2 is not built into `libhadoop`, you need to put `libbz2.1` to the lib search path. 

You can get a built libbz2 lib from the artifacts at https://github.com/7c00/libhadoop-macos-arm64/actions/runs/2637081130, and then add an environment variable `DYLD_LIBRARY_PATH=path/to/download/lib/dir`.

**Comment by beinan** [comment]
> @beinan bzip2 is not built into `libhadoop`, you need to put `libbz2.1` to the lib search path.
> 
> You can get a built libbz2 lib from the artifacts at https://github.com/7c00/libhadoop-macos-arm64/actions/runs/2637081130, and then add an environment variable `DYLD_LIBRARY_PATH=path/to/download/lib/dir`.

Thank you for the tips!   should we include bzip in the libhadoop?  I guess the x86 llibhadoop is including the the bzip, am I right?

**Comment by 7c00** [comment]
@beinan I think bzip2 is not built into libhadoop in any architectures. As the code shows, hadoop will always try to load a  bzip2 lib dynamically when need.

https://github.com/apache/hadoop/blob/e446276a9ad3a7ab31692a12d220af42ee2e0e79/hadoop-common-project/hadoop-common/src/main/native/src/org/apache/hadoop/io/compress/bzip2/Bzip2Compressor.c#L60-L74

**Comment by yingsu00** [comment]
cc @wanglinsong

**Comment by yingsu00** [comment]
@7c00 Sorry for the big delay in merging this PR. Could you include the Hadoop version in the PR message? Also, I wonder if you want to update it again since many months have passed and it may have a new version now.

**Comment by yingsu00** [comment]
> @7c00 Sorry for the big delay in merging this PR. Could you include the Hadoop version in the PR message? Also, I wonder if you want to update it again since many months have passed and it may have a new version now.

**Comment by yingsu00** [comment]
@imjalpreet @wanglinsong Will you be able to test if these libs work?

**Comment by 7c00** [comment]
> @7c00 Sorry for the big delay in merging this PR. Could you include the Hadoop version in the PR message? Also, I wonder if you want to update it again since many months have passed and it may have a new version now.

@yingsu00 updated the commit message. The Hadoop lib is built upon Hadoop 2.7.4, which is the same as the version from pom in master branch.

**Comment by Akanksha-kedia** [comment]
i m still facing issue chip : Apple M1 Pro but issue :
java.lang.ExceptionInInitializerError
at io.prestosql.plugin.hive.HdfsEnvironment$$FastClassByGuice$$2c8553d4.newInstance()
at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
at com.google.inject.Guice.createInjector(Guice.java:87)
at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:276)
at io.prestosql.plugin.hive.InternalHiveConnectorFactory.createConnector(InternalHiveConnectorFactory.java:117)
at io.prestosql.plugin.hive.InternalHiveConnectorFactory.createConnector(InternalHiveConnectorFactory.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at io.prestosql.plugin.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:63)
at io.prestosql.connector.ConnectorManager.createConnector(ConnectorManager.java:353)
at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:212)
at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:204)
at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:190)
at io.prestosql.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
at io.prestosql.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
at io.prestosql.server.Server.doStart(Server.java:119)
at io.prestosql.server.Server.lambda$start$0(Server.java:73)
at io.prestosql.$gen.Presto_unknown____20240504_042839_1.run(Unknown Source)
at io.prestosql.server.Server.start(Server.java:73)
at io.prestosql.server.PrestoServer.main(PrestoServer.java:38)
Caused by: java.lang.RuntimeException: failed to load Hadoop native library
at io.prestosql.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:59)
at io.prestosql.plugin.hive.HdfsEnvironment.(HdfsEnvironment.java:39)
... 52 more
Caused by: java.lang.RuntimeException: library not found: /nativelib/Mac_OS_X-aarch64/libhadoop.dylib
at io.prestosql.hadoop.HadoopNative.loadLibrary(HadoopNative.java:89)
at io.prestosql.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:47)
... 53 more

Screenshot 2024-05-04 at 10 01 10 AM
also i tried exporting export DYLD_LIBRARY_PATH=/path/

Downloaded the library from the provided link and saved it to a suitable directory, say /Users/ak/lib.

Set the DYLD_LIBRARY_PATH environment variable to include the directory where saved the libhadoop.dylib file:

export DYLD_LIBRARY_PATH=/Users/ak/lib

**Pull request merged**
