### PR TITLE
Add Linux-aarch64 resource to support arm

### PR DESCRIPTION
**Pull request by JunLuo**
Add Linux-aarch64 resource to support arm.

### CODE REVIEW

**Comment by striverpan** [comment]
@imjalpreet @beinan   First, building the hadoop source code in ARM environment. In that case, we can get nativelib.so file . Then create a directory in the resource  path of project  [presto-hadoop-apache2](https://github.com/prestodb/presto-hadoop-apache2) and copy the the nativelib.so file into this directory.

**Review by beinan — COMMENTED** [review]
looks good, I'm just wondering how did you get/build these two native lib?  is there any source or instructions to build these lib?

**Comment by JunLuo** [comment]
hi, @beinan .In our solution, we need compile protobuf 2.5 which depended by hadoop 2.7.4. Then compile and package protobuf in hadoop-common project to generate libhadoop.so. There are no additional resources in this project.

**Comment by beinan** [comment]
> hi, @beinan .In our solution, we need compile protobuf 2.5 which depended by hadoop 2.7.4. Then compile and package protobuf in hadoop-common project to generate libhadoop.so. There are no additional resources in this project.

Thank you @JunLuo !  Is it possible to provide step by step instructions for the compile and package?  Just wanna make the build process to be reproducible in case we might upgrade the hadoop version in the future.  Thanks a lot!

**Review by beinan — COMMENTED** [review]
This libraries are not working on centos 7,  looks like the gcc used for these libs are too new,  I will try to re-build them with an older version of gcc for better compatibility.

**Comment by ChunxuTang** [comment]
Hi @JunLuo, thanks for your contribution!

As the latest PR for `linux-aarch64` has been merged (https://github.com/prestodb/presto-hadoop-apache2/pull/60), I'm closing this PR. Meanwhile, I'm opening a PR for Presto side modifications (https://github.com/prestodb/presto/pull/18960).

Feel free to ping me if you have any questions.

**Pull request closed without merging**
